.list off
.ifndef SONG_SCRIPT_INC
SONG_SCRIPT_INC = 1

.global SongScript, SongScriptPtrs

; song ids
.enum SONG
        AHEAD_ON_OUR_WAY                ; $00
        THE_FIERCE_BATTLE               ; $01
        A_PRESENTIMENT                  ; $02
        GO_GO_BOKO                      ; $03
        PIRATES_AHOY                    ; $04
        TENDERNESS_IN_THE_AIR           ; $05
        FATE_IN_HAZE                    ; $06
        CRITTER_TRIPPER_FRITTER         ; $07
        THE_PRELUDE                     ; $08
        THE_LAST_BATTLE                 ; $09
        REQUIEM                         ; $0a
        NOSTALGIA                       ; $0b
        CURSED_EARTHS                   ; $0c
        LENNAS_THEME                    ; $0d
        VICTORYS_FANFARE                ; $0e
        DECEPTION                       ; $0f
        THE_DAY_WILL_COME               ; $10
        SILENCE                         ; $11
        EXDEATHS_CASTLE                 ; $12
        MY_HOME_SWEET_HOME              ; $13
        WALTZ_SUOMI                     ; $14
        SEALED_AWAY                     ; $15
        THE_FOUR_WARRIORS_OF_DAWN       ; $16
        DANGER                          ; $17
        THE_FIREPOWERED_SHIP            ; $18
        AS_I_FEEL_YOU_FEEL              ; $19
        MAMBO_DE_CHOCOBO                ; $1a
        MUSIC_BOX_SONG                  ; $1b
        INTENSION_OF_THE_EARTH          ; $1c
        THE_DRAGON_SPREADS_ITS_WINGS    ; $1d
        BEYOND_THE_DEEP_BLUE_SEA        ; $1e
        PRELUDE_OF_EMPTY_SKIES          ; $1f
        SEARCHING_FOR_THE_LIGHT         ; $20
        HARVEST                         ; $21
        GILGAMESH                       ; $22
        FOUR_VALIANT_HEARTS             ; $23
        THE_BOOK_OF_SEALINGS            ; $24
        WHAT                            ; $25
        HURRY_HURRY                     ; $26
        UNKNOWN_LANDS                   ; $27
        THE_AIRSHIP                     ; $28
        FANFARE_1                       ; $29
        FANFARE_2                       ; $2a
        THE_BATTLE                      ; $2b
        WALKING_THE_SNOWY_MOUNTAINS     ; $2c
        THE_EVIL_LORD_EXDEATH           ; $2d
        THE_CASTLE_OF_DAWN              ; $2e
        IM_A_DANCER                     ; $2f
        REMINISCENCE                    ; $30
        RUN                             ; $31
        THE_ANCIENT_LIBRARY             ; $32
        ROYAL_PALACE                    ; $33
        GOOD_NIGHT                      ; $34
        PIANO_LESSON_1                  ; $35
        PIANO_LESSON_2                  ; $36
        PIANO_LESSON_3                  ; $37
        PIANO_LESSON_4                  ; $38
        PIANO_LESSON_5                  ; $39
        PIANO_LESSON_6                  ; $3a
        PIANO_LESSON_7                  ; $3b
        PIANO_LESSON_8                  ; $3c
        MUSICA_MACHINA                  ; $3d
        A_METEOR_IS_FALLING             ; $3e
        THE_LAND_UNKNOWN                ; $3f
        THE_DECISIVE_BATTLE             ; $40
        THE_SILENT_BEYOND               ; $41
        DEAR_FRIENDS                    ; $42
        FINAL_FANTASY                   ; $43
        A_NEW_ORIGIN                    ; $44
        CRICKETS_CHIRPING               ; $45
        A_SHORE                         ; $46
        THE_TIDE_ROLLS_IN               ; $47
.endenum

.scope SongScript

; ##############################################################################
; ###          AUTOMATICALLY GENERATED CODE, DO NOT MODIFY MANUALLY          ###
; ##############################################################################


; ##############################################################################

.endscope

.endif
.list on
